/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Pengenalan',
    },
    {
      "Penggunaan API": [
        'penggunaan/dasar', 
        'penggunaan/field',
        'penggunaan/keyword',
        'penggunaan/perawi',
        'penggunaan/page',
        'penggunaan/id',
      ],
    },
    {
      type: 'doc',
      id: 'stats',
      label: 'Statistics API',
    },
    {
      "Lainnya": ['lainnya/demo']
    }
  ],
   
};
